# Generated by Django 6.0.2 on 2026-02-15 18:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_guide', models.TextField()),
                ('database_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maqola banki',
                'verbose_name_plural': 'Maqolalar banki',
                'db_table': 'article_bank',
            },
        ),
        migrations.CreateModel(
            name='BuxduOlympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='buxdu_olympiads/images/')),
                ('subject', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('program_file', models.FileField(upload_to='buxdu_olympiads/programs/')),
                ('registration_link_1', models.URLField()),
                ('registration_link_2', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BuxDU olimpiadasi',
                'verbose_name_plural': 'BuxDU olimpiadalari',
                'db_table': 'buxdu_olympiads',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BuxduOlympiadWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='buxdu_olympiad_winners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "BuxDU olimpiada g'olibi",
                'verbose_name_plural': "BuxDU olimpiada g'oliblari",
                'db_table': 'buxdu_olympiad_winners',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='BuxduScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('regulation_file', models.FileField(upload_to='scholarships/regulations/')),
                ('application_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BuxDU stipendiyasi',
                'verbose_name_plural': 'BuxDU stipendiyalari',
                'db_table': 'buxdu_scholarships',
            },
        ),
        migrations.CreateModel(
            name='BuxduWinnerDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('scholarship_type', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='buxdu_winners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BuxDU sovrindorlar bazasi',
                'verbose_name_plural': 'BuxDU sovrindorlar bazalari',
                'db_table': 'buxdu_winner_database',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('republic', 'Respublika'), ('international', 'Xalqaro')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('information_letter', models.FileField(upload_to='conferences/info_letters/')),
                ('organizer_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konferensiya',
                'verbose_name_plural': 'Konferensiyalar',
                'db_table': 'conferences',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trainer', models.CharField(max_length=255)),
                ('goal', models.TextField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='courses/presentations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='DissertationBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_type', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dissertatsiya banki',
                'verbose_name_plural': 'Dissertatsiyalar banki',
                'db_table': 'dissertation_bank',
            },
        ),
        migrations.CreateModel(
            name='OakDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('local', 'Mahalliy'), ('international', 'Xalqaro')], max_length=20)),
                ('journal_name', models.CharField(max_length=255)),
                ('fields', models.TextField()),
                ('database_link', models.URLField()),
                ('editorial_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OAK bazasi',
                'verbose_name_plural': 'OAK bazalari',
                'db_table': 'oak_database',
            },
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('information_letter', models.FileField(blank=True, null=True, upload_to='olympiads/info_letters/')),
                ('registration_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Olimpiada',
                'verbose_name_plural': 'Olimpiadalar',
                'db_table': 'olympiads',
            },
        ),
        migrations.CreateModel(
            name='ResearcherRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='regulations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tadqiqotchi nizomi',
                'verbose_name_plural': 'Tadqiqotchilar nizomlari',
                'db_table': 'researcher_regulations',
            },
        ),
        migrations.CreateModel(
            name='StateScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('regulation_link', models.URLField()),
                ('application_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Davlat stipendiyasi',
                'verbose_name_plural': 'Davlat stipendiyalari',
                'db_table': 'state_scholarships',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('google_form_link', models.URLField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
                'db_table': 'surveys',
            },
        ),
        migrations.CreateModel(
            name='TalentedStudentDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='talented_students/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Iqtidorli talabalar bazasi',
                'verbose_name_plural': 'Iqtidorli talabalar bazalari',
                'db_table': 'talented_students_database',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_text', models.TextField()),
                ('date', models.DateField()),
                ('detailed_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'db_table': 'announcements',
                'ordering': ['-date'],
            },
        ),
    ]
