# Generated by Django 6.0.2 on 2026-02-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='detailed_text',
            field=models.TextField(verbose_name='Batafsil matn'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='short_text',
            field=models.TextField(verbose_name='Qisqa matn'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
    ]
