# Generated by Django 6.0.2 on 2026-02-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_announcement_image_alter_announcement_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Rasm (fayl)'),
        ),
    ]
