# Generated by Django 6.0.2 on 2026-02-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20260216_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='active', max_length=50, verbose_name='Status'),
        ),
    ]
