# Generated by Django 6.0.2 on 2026-02-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_profile_image_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='talaba', max_length=50, verbose_name='Status'),
        ),
    ]
