# Generated by Django 6.0.2 on 2026-02-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': "So'rovnoma", 'verbose_name_plural': "So'rovnomalar"},
        ),
        migrations.AlterModelOptions(
            name='talentedstudentdatabase',
            options={'ordering': ['-academic_year'], 'verbose_name': 'Iqtidorli talabalar bazasi', 'verbose_name_plural': 'Iqtidorli talabalar bazasi'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='google_form_link',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='note',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='talentedstudentdatabase',
            name='name',
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='survey',
            name='link',
            field=models.URLField(default='https://forms.google.com', verbose_name='Havola'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(default="So'rovnoma", max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='talentedstudentdatabase',
            name='file_name',
            field=models.CharField(default="Iqtidorli talabalar ro'yxati", max_length=255, verbose_name='Fayl nomi'),
        ),
        migrations.AlterField(
            model_name='talentedstudentdatabase',
            name='academic_year',
            field=models.CharField(max_length=50, verbose_name="O'quv yili"),
        ),
        migrations.AlterField(
            model_name='talentedstudentdatabase',
            name='file',
            field=models.FileField(upload_to='talented_students/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='talentedstudentdatabase',
            name='file_format',
            field=models.CharField(default='PDF', max_length=10, verbose_name='Format'),
        ),
    ]
