# Generated by Django 6.0.2 on 2026-02-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_survey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='type',
            field=models.CharField(choices=[('international', 'Xalqaro'), ('republic', 'Respublika'), ('online', 'Onlayn')], default='international', max_length=20),
        ),
    ]
