# Generated by Django 6.0.2 on 2026-02-15 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_olympiad_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='course',
            name='presentation_file',
        ),
        migrations.RemoveField(
            model_name='course',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Kurs rasmi'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='course',
            name='module_count',
            field=models.IntegerField(default=1, verbose_name='Modullar soni'),
        ),
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.IntegerField(default=70, verbose_name="O'tish bali (%)"),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='', verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='course',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/tests/', verbose_name='Test fayli (DOCX)'),
        ),
        migrations.AddField(
            model_name='course',
            name='time_per_question',
            field=models.IntegerField(default=2, verbose_name='Har bir savol uchun vaqt (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kurs nomi'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Modul raqami')),
                ('name', models.CharField(max_length=255, verbose_name='Modul nomi')),
                ('description', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('presentation', models.FileField(blank=True, null=True, upload_to='modules/presentations/', verbose_name='Taqdimot')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'db_table': 'modules',
                'ordering': ['course', 'number'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Savol raqami')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'db_table': 'questions',
                'ordering': ['course', 'number'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Ball')),
                ('total_questions', models.IntegerField(verbose_name='Jami savollar')),
                ('correct_answers', models.IntegerField(verbose_name="To'g'ri javoblar")),
                ('percentage', models.IntegerField(verbose_name='Foiz')),
                ('passed', models.BooleanField(default=False, verbose_name="O'tdi")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='main.course', verbose_name='Kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'db_table': 'user_test_results',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqt')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugatilgan')),
                ('test_score', models.IntegerField(blank=True, null=True, verbose_name='Test natijasi (foiz)')),
                ('test_passed', models.BooleanField(default=False, verbose_name="Test o'tdi")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='main.course', verbose_name='Kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi kurs progressi',
                'verbose_name_plural': 'Foydalanuvchi kurs progresslari',
                'db_table': 'user_course_progress',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_presentation', models.BooleanField(default=False, verbose_name="Taqdimot ko'rildi")),
                ('watched_video', models.BooleanField(default=False, verbose_name="Video ko'rildi")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqt')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugatilgan')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='main.module', verbose_name='Modul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi modul progressi',
                'verbose_name_plural': 'Foydalanuvchi modul progresslari',
                'db_table': 'user_module_progress',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
