# Generated by Django 6.0.2 on 2026-02-16 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_course_options_remove_course_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='certificates/', verbose_name='Sertifikat fayli')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='main.course', verbose_name='Kurs')),
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='main.usertestresult', verbose_name='Test natijasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
