# Generated by Django 6.0.2 on 2026-02-16 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Test to'plami",
                'verbose_name_plural': "Test to'plamlari",
                'db_table': 'test_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['test_set', 'number'], 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='test_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.testset', verbose_name="Test to'plami"),
        ),
        migrations.AddField(
            model_name='question',
            name='test_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.testset', verbose_name="Test to'plami"),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test_set', 'number')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
    ]
