# Generated by Django 6.0.2 on 2026-02-16 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_testset_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assessment_next_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Keyingi urinish vaqti'),
        ),
        migrations.AddField(
            model_name='user',
            name='assessment_score',
            field=models.FloatField(default=0, verbose_name='Saralash testi natijasi (%)'),
        ),
        migrations.AddField(
            model_name='user',
            name='assessment_status',
            field=models.CharField(default='oddiy', max_length=20, verbose_name='Talaba holati'),
        ),
        migrations.AddField(
            model_name='user',
            name='assessment_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saralash testi topshirilgan vaqt'),
        ),
        migrations.CreateModel(
            name='AssessmentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Iqtidorli talabamisiz?', max_length=255, verbose_name='Test nomi')),
                ('description', models.TextField(verbose_name="Test haqida ma'lumot")),
                ('time_limit', models.IntegerField(default=60, verbose_name='Vaqt limiti (daqiqalarda)')),
                ('pass_percentage', models.IntegerField(default=60, verbose_name="O'tish foizi")),
                ('retry_delay_hours', models.IntegerField(default=1, verbose_name='Qayta urinish uchun kutish vaqti (soatlarda)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_tests', to='main.testset', verbose_name="Test to'plami")),
            ],
            options={
                'verbose_name': 'Saralash testi',
                'verbose_name_plural': 'Saralash testlari',
                'db_table': 'assessment_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Ball')),
                ('total_questions', models.IntegerField(verbose_name='Jami savollar')),
                ('correct_answers', models.IntegerField(verbose_name="To'g'ri javoblar")),
                ('percentage', models.FloatField(verbose_name='Foiz')),
                ('passed', models.BooleanField(default=False, verbose_name="O'tdi")),
                ('time_taken', models.IntegerField(blank=True, null=True, verbose_name='Sarflangan vaqt (soniyalarda)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('assessment_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.assessmenttest', verbose_name='Saralash testi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Saralash testi natijasi',
                'verbose_name_plural': 'Saralash testi natijalari',
                'db_table': 'assessment_test_results',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
