# Generated by Django 6.0.2 on 2026-02-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_assessment_next_attempt_user_assessment_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.CharField(help_text="E'lon muallifining ismi (masalan: X.U.Mirovna)", max_length=255, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(help_text="E'lon sanasini tanlang", verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='detailed_text',
            field=models.TextField(help_text="E'lonning to'liq matni", verbose_name='Batafsil matn'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text="E'lon uchun rasm yuklang (JPG, PNG)", null=True, upload_to='announcements/', verbose_name='Rasm (fayl)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, help_text='Yoki rasm URL manzilini kiriting', null=True, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='short_text',
            field=models.TextField(help_text="E'lonning qisqacha matni (2-3 qator)", verbose_name='Qisqa matn'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text="E'lon sarlavhasini kiriting", max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text="Bu to'g'ri javobmi? (faqat bitta javob to'g'ri bo'lishi kerak)", verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Javobni tegishli savolga biriktiring', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(help_text='Javob variantini kiriting', max_length=500, verbose_name='Javob matni'),
        ),
        migrations.AlterField(
            model_name='articlebank',
            name='database_link',
            field=models.URLField(help_text='Maqolalar bazasiga havola', verbose_name='Baza havolasi'),
        ),
        migrations.AlterField(
            model_name='articlebank',
            name='name',
            field=models.CharField(help_text='Maqola bazasi nomini kiriting', max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='articlebank',
            name='short_guide',
            field=models.TextField(help_text="Bazadan foydalanish bo'yicha qisqa qo'llanma", verbose_name="Qisqa qo'llanma"),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='description',
            field=models.TextField(help_text="Test haqida batafsil ma'lumot va ko'rsatmalar", verbose_name="Test haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Test faolmi? (belgilangan bo'lsa, foydalanuvchilar ko'radi)", verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='pass_percentage',
            field=models.IntegerField(default=60, help_text="Testni o'tish uchun minimal foiz (masalan: 60)", verbose_name="O'tish foizi"),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='retry_delay_hours',
            field=models.IntegerField(default=1, help_text='Testni qayta topshirish uchun kutish vaqti (soatlarda, masalan: 1)', verbose_name='Qayta urinish uchun kutish vaqti (soatlarda)'),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='test_set',
            field=models.ForeignKey(blank=True, help_text="Tayyor test to'plamini tanlang", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_tests', to='main.testset', verbose_name="Test to'plami"),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='Test uchun berilgan vaqt (daqiqalarda, masalan: 60)', verbose_name='Vaqt limiti (daqiqalarda)'),
        ),
        migrations.AlterField(
            model_name='assessmenttest',
            name='title',
            field=models.CharField(default='Iqtidorli talabamisiz?', help_text='Saralash testi nomini kiriting', max_length=255, verbose_name='Test nomi'),
        ),
        migrations.AlterField(
            model_name='buxduolympiad',
            name='date',
            field=models.DateField(help_text="Olimpiada o'tkaziladigan sana", verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='buxduolympiad',
            name='description',
            field=models.TextField(help_text="Olimpiada haqida batafsil ma'lumot", verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='buxduolympiad',
            name='image',
            field=models.ImageField(help_text='Olimpiada uchun rasm yuklang (JPG, PNG)', upload_to='buxdu_olympiads/images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='buxduolympiad',
            name='program_file',
            field=models.FileField(help_text='Olimpiada dasturini yuklang (PDF)', upload_to='buxdu_olympiads/programs/', verbose_name='Dastur fayli'),
        ),
        migrations.AlterField(
            model_name='buxduolympiad',
            name='registration_link_1',
            field=models.URLField(help_text="Birinchi ro'yxatdan o'tish havolasi", verbose_name="Ro'yxatdan o'tish 1"),
        ),
        migrations.AlterField(
            model_name='buxduolympiad',
            name='registration_link_2',
            field=models.URLField(blank=True, help_text="Ikkinchi ro'yxatdan o'tish havolasi (ixtiyoriy)", null=True, verbose_name="Ro'yxatdan o'tish 2"),
        ),
        migrations.AlterField(
            model_name='buxduolympiad',
            name='subject',
            field=models.CharField(help_text='Olimpiada fani (masalan: Fizika)', max_length=255, verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='buxduolympiadwinner',
            name='academic_year',
            field=models.CharField(help_text='Masalan: 2023-2024', max_length=20, verbose_name="O'quv yili"),
        ),
        migrations.AlterField(
            model_name='buxduolympiadwinner',
            name='file',
            field=models.FileField(help_text="G'oliblar ro'yxatini yuklang (PDF, XLSX)", upload_to='buxdu_olympiad_winners/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='buxduolympiadwinner',
            name='file_name',
            field=models.CharField(help_text="G'oliblar ro'yxati fayl nomi", max_length=255, verbose_name='Fayl nomi'),
        ),
        migrations.AlterField(
            model_name='buxduolympiadwinner',
            name='olympiad_name',
            field=models.CharField(help_text='Olimpiada nomini kiriting', max_length=255, verbose_name='Olimpiada nomi'),
        ),
        migrations.AlterField(
            model_name='buxduolympiadwinner',
            name='subject',
            field=models.CharField(help_text='Olimpiada fani (masalan: Matematika)', max_length=255, verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='buxduscholarship',
            name='application_link',
            field=models.URLField(help_text='Onlayn ariza topshirish uchun havola', verbose_name='Ariza topshirish havolasi'),
        ),
        migrations.AlterField(
            model_name='buxduscholarship',
            name='name',
            field=models.CharField(help_text='BuxDU stipendiya nomini kiriting', max_length=255, verbose_name='Stipendiya nomi'),
        ),
        migrations.AlterField(
            model_name='buxduscholarship',
            name='regulation_file',
            field=models.FileField(help_text='Stipendiya nizomini yuklang (PDF, DOCX)', upload_to='scholarships/regulations/', verbose_name='Nizom fayli'),
        ),
        migrations.AlterField(
            model_name='buxduscholarship',
            name='short_description',
            field=models.TextField(help_text="Stipendiya shartlari va talablari haqida ma'lumot", verbose_name='Qisqacha tavsif'),
        ),
        migrations.AlterField(
            model_name='buxduwinnerdatabase',
            name='academic_year',
            field=models.CharField(help_text='Masalan: 2023-2024', max_length=20, verbose_name="O'quv yili"),
        ),
        migrations.AlterField(
            model_name='buxduwinnerdatabase',
            name='file',
            field=models.FileField(help_text="G'oliblar ro'yxatini yuklang (PDF, XLSX)", upload_to='buxdu_winners/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='buxduwinnerdatabase',
            name='file_name',
            field=models.CharField(help_text="G'oliblar ro'yxati fayl nomi", max_length=255, verbose_name='Fayl nomi'),
        ),
        migrations.AlterField(
            model_name='buxduwinnerdatabase',
            name='scholarship_type',
            field=models.CharField(help_text='Stipendiya turini kiriting (masalan: BuxDU rektori stipendiyasi)', max_length=255, verbose_name='Stipendiya turi'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='information_letter',
            field=models.FileField(help_text="Konferensiya haqida ma'lumot xati (PDF)", upload_to='conferences/info_letters/', verbose_name="Ma'lumot xati"),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(help_text='Konferensiya nomini kiriting', max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='organizer_link',
            field=models.URLField(help_text='Tashkilotchi tashkilot sahifasiga havola', verbose_name='Tashkilotchi havolasi'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='type',
            field=models.CharField(choices=[('republic', 'Respublika'), ('international', 'Xalqaro')], help_text='Konferensiya turini tanlang', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Kurs uchun rasm yuklang (PNG, JPG)', null=True, upload_to='courses/', verbose_name='Kurs rasmi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Kurs faolmi? (belgilangan bo'lsa, foydalanuvchilar ko'radi)", verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='course',
            name='module_count',
            field=models.IntegerField(default=1, help_text="Kursda nechta modul bo'lishini kiriting (masalan: 5)", verbose_name='Modullar soni'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text="Kursning to'liq nomini kiriting (masalan: Python dasturlash asoslari)", max_length=255, verbose_name='Kurs nomi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='passing_score',
            field=models.IntegerField(default=70, help_text="Testni o'tish uchun minimal ball (%, masalan: 70)", verbose_name="O'tish bali (%)"),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='', help_text="Kurs haqida qisqacha ma'lumot (3-5 jumla)", verbose_name='Qisqacha tavsif'),
        ),
        migrations.AlterField(
            model_name='course',
            name='test_file',
            field=models.FileField(blank=True, help_text='DOCX formatdagi test faylini yuklang (ixtiyoriy)', null=True, upload_to='courses/tests/', verbose_name='Test fayli (DOCX)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='test_set',
            field=models.ForeignKey(blank=True, help_text="Kurs uchun tayyor test to'plamini tanlang", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.testset', verbose_name="Test to'plami"),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_per_question',
            field=models.IntegerField(default=2, help_text='Har bir savol uchun berilgan vaqt (daqiqalarda, masalan: 2)', verbose_name='Har bir savol uchun vaqt (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='dissertationbank',
            name='database_type',
            field=models.CharField(help_text='Dissertatsiya bazasi turi (masalan: DSc, PhD)', max_length=255, verbose_name='Baza turi'),
        ),
        migrations.AlterField(
            model_name='dissertationbank',
            name='direction',
            field=models.CharField(help_text="Ilmiy yo'nalish (masalan: Pedagogika, Iqtisodiyot)", max_length=255, verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='dissertationbank',
            name='link',
            field=models.URLField(help_text='Dissertatsiya bazasiga havola', verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(help_text="Modulni tegishli kursga bog'lash", on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(help_text="Modul haqida qisqa ma'lumot yozing", verbose_name="Qisqacha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='Modul nomini kiriting (masalan: Kirish, Asosiy tushunchalar)', max_length=255, verbose_name='Modul nomi'),
        ),
        migrations.AlterField(
            model_name='module',
            name='number',
            field=models.IntegerField(help_text='Modul tartib raqami (1, 2, 3...)', verbose_name='Modul raqami'),
        ),
        migrations.AlterField(
            model_name='module',
            name='presentation',
            field=models.FileField(blank=True, help_text='PowerPoint yoki PDF taqdimot fayli', null=True, upload_to='modules/presentations/', verbose_name='Taqdimot'),
        ),
        migrations.AlterField(
            model_name='module',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video havolasini joylashtiring (masalan: https://youtube.com/watch?v=...)', null=True, verbose_name='YouTube video URL'),
        ),
        migrations.AlterField(
            model_name='oakdatabase',
            name='database_link',
            field=models.URLField(help_text='Jurnal bazasiga havola (https://...)', verbose_name='Baza havolasi'),
        ),
        migrations.AlterField(
            model_name='oakdatabase',
            name='editorial_link',
            field=models.URLField(help_text='Tahririyat sahifasiga havola', verbose_name='Tahririyat havolasi'),
        ),
        migrations.AlterField(
            model_name='oakdatabase',
            name='fields',
            field=models.TextField(help_text="Jurnal qabul qiladigan yo'nalishlar (vergul bilan ajratib yozing)", verbose_name="Yo'nalishlar"),
        ),
        migrations.AlterField(
            model_name='oakdatabase',
            name='journal_name',
            field=models.CharField(help_text='OAK jurnali nomini kiriting', max_length=255, verbose_name='Jurnal nomi'),
        ),
        migrations.AlterField(
            model_name='oakdatabase',
            name='type',
            field=models.CharField(choices=[('local', 'Mahalliy'), ('international', 'Xalqaro')], help_text='Jurnal turini tanlang (Mahalliy yoki Xalqaro)', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='country',
            field=models.CharField(help_text="Olimpiada o'tkaziladigan davlat (masalan: O'zbekiston, AQSh)", max_length=100, verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='information_letter',
            field=models.FileField(blank=True, help_text="Olimpiada haqida rasmiy ma'lumot xati (PDF)", null=True, upload_to='olympiads/info_letters/', verbose_name="Ma'lumot xati"),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='name',
            field=models.CharField(help_text="Olimpiadaning to'liq nomi", max_length=255, verbose_name='Olimpiada nomi'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='registration_link',
            field=models.URLField(help_text="Olimpiadaga ro'yxatdan o'tish uchun havola", verbose_name="Ro'yxatdan o'tish havolasi"),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='short_description',
            field=models.TextField(help_text="Olimpiada haqida qisqa ma'lumot", verbose_name='Qisqacha tavsif'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='subject',
            field=models.CharField(help_text='Olimpiada fani (masalan: Matematika, Fizika)', max_length=255, verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='type',
            field=models.CharField(choices=[('international', 'Xalqaro'), ('republic', 'Respublika'), ('online', 'Onlayn')], default='international', help_text='Olimpiada turini tanlang', max_length=20, verbose_name='Olimpiada turi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(help_text='Savol tartib raqami (1, 2, 3...)', verbose_name='Savol raqami'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_set',
            field=models.ForeignKey(blank=True, help_text="Savolni tegishli test to'plamiga biriktiring", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.testset', verbose_name="Test to'plami"),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text="Savolning to'liq matnini kiriting", verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='researcherregulation',
            name='file',
            field=models.FileField(help_text='Nizom faylini yuklang (PDF, DOCX)', upload_to='regulations/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='researcherregulation',
            name='regulation_name',
            field=models.CharField(help_text='Nizom nomini kiriting', max_length=255, verbose_name='Nizom nomi'),
        ),
        migrations.AlterField(
            model_name='statescholarship',
            name='application_link',
            field=models.URLField(help_text='Ariza topshirish uchun havola (https://...)', verbose_name='Ariza topshirish havolasi'),
        ),
        migrations.AlterField(
            model_name='statescholarship',
            name='name',
            field=models.CharField(help_text='Stipendiya nomini kiriting (masalan: Prezident stipendiyasi)', max_length=255, verbose_name='Stipendiya nomi'),
        ),
        migrations.AlterField(
            model_name='statescholarship',
            name='regulation_link',
            field=models.URLField(help_text='Stipendiya nizomiga havola (https://...)', verbose_name='Nizom havolasi'),
        ),
        migrations.AlterField(
            model_name='statescholarship',
            name='short_description',
            field=models.TextField(help_text="Stipendiya haqida qisqa ma'lumot (kimlar uchun, qancha miqdor)", verbose_name='Qisqacha tavsif'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, default='', help_text="So'rovnoma haqida qisqa ma'lumot", verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, help_text="So'rovnoma faolmi? (belgilangan bo'lsa, saytda ko'rsatiladi)", verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='link',
            field=models.URLField(default='https://forms.google.com', help_text="Google Forms yoki boshqa so'rovnoma havolasi", verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(default="So'rovnoma", help_text="So'rovnoma sarlavhasini kiriting", max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='talentedstudentdatabase',
            name='academic_year',
            field=models.CharField(help_text="O'quv yilini kiriting (masalan: 2023-2024)", max_length=50, verbose_name="O'quv yili"),
        ),
        migrations.AlterField(
            model_name='talentedstudentdatabase',
            name='file',
            field=models.FileField(help_text="Iqtidorli talabalar ro'yxatini yuklang (PDF, DOCX, XLSX)", upload_to='talented_students/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='talentedstudentdatabase',
            name='file_format',
            field=models.CharField(default='PDF', help_text='Fayl formati (PDF, DOCX, XLSX)', max_length=10, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='talentedstudentdatabase',
            name='file_name',
            field=models.CharField(default="Iqtidorli talabalar ro'yxati", help_text='Fayl nomi (masalan: Iqtidorli talabalar 2023-2024)', max_length=255, verbose_name='Fayl nomi'),
        ),
        migrations.AlterField(
            model_name='testset',
            name='description',
            field=models.TextField(blank=True, help_text="Test to'plami haqida qisqa ma'lumot", null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='testset',
            name='name',
            field=models.CharField(help_text="Test to'plami nomini kiriting (masalan: Python asoslari testi)", max_length=200, verbose_name='Test nomi'),
        ),
    ]
