# Generated by Django 6.0.2 on 2026-02-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_buxduolympiad_result_file_buxduolympiadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.AddField(
            model_name='user',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('', 'Tanlanmagan'), ('bakalavr', 'Bakalavr'), ('magistr', 'Magistr'), ('phd', 'PhD (Falsafa doktori)'), ('dsc', 'DSc (Fan doktori)')], default='', max_length=20, verbose_name='Ilmiy daraja'),
        ),
        migrations.AddField(
            model_name='user',
            name='residence_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yashash xudud'),
        ),
    ]
