# Generated by Django 6.0.2 on 2026-02-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_user_region_user_academic_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="O'qigan/O'qiyotgan joy"),
        ),
    ]
