# Generated by Django 6.0.2 on 2026-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Olimpiadalar sahifasining yuqori qismida ko'rsatiladigan rasm (tavsiya: 800x600px)", null=True, upload_to='olympiads/hero_images/', verbose_name='Hero rasm'),
        ),
    ]
