# Generated by Django 6.0.2 on 2026-02-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_olympiad_hero_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiad',
            options={'ordering': ['date'], 'verbose_name': 'Olimpiada', 'verbose_name_plural': 'Olimpiadalar'},
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='date',
            field=models.DateField(default='2026-12-31', help_text="Olimpiada o'tkaziladigan sana", verbose_name='Olimpiada sanasi'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='image',
            field=models.ImageField(blank=True, help_text="Olimpiada kartasida ko'rsatiladigan rasm (tavsiya: 400x300px)", null=True, upload_to='olympiads/images/', verbose_name='Olimpiada rasmi'),
        ),
    ]
