# Generated by Django 6.0.2 on 2026-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_olympiad_options_remove_olympiad_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fakultet'),
        ),
    ]
