# Generated by Django 6.0.2 on 2026-05-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_add_faculty_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Kitob/Adabiyot nomi')),
                ('author', models.CharField(max_length=300, verbose_name='Muallif')),
                ('field', models.CharField(choices=[('', 'Soha tanlang'), ('matematika', 'Matematika'), ('fizika', 'Fizika'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya'), ('informatika', 'Informatika va axborot texnologiyalari'), ('tarix', 'Tarix'), ('filologiya', 'Filologiya'), ('xorijiy_tillar', 'Xorijiy tillar'), ('iqtisodiyot', 'Iqtisodiyot'), ('huquq', 'Huquq'), ('tibbiyot', 'Tibbiyot'), ('pedagogika', 'Pedagogika'), ('psixologiya', 'Psixologiya'), ('sport', 'Sport va jismoniy tarbiya'), ('texnika', 'Texnika va texnologiya'), ('qishloq_xojaligi', "Qishloq xo'jaligi"), ('san_at', "San'at va dizayn"), ('boshqa', 'Boshqa')], default='', max_length=100, verbose_name='Soha')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='literature/covers/', verbose_name='Muqova rasmi')),
                ('file', models.FileField(blank=True, null=True, upload_to='literature/files/', verbose_name='Fayl (PDF/PPT/Word)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Internet manzili')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Qisqacha tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adabiyot',
                'verbose_name_plural': 'Adabiyotlar',
                'db_table': 'literature',
                'ordering': ['-created_at'],
            },
        ),
    ]
