# Generated by Django 6.0.2 on 2026-05-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_literature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('position', models.CharField(help_text='Masalan: Fizika-matematika fanlari doktori, professor', max_length=255, verbose_name='Lavozimi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='supervisors/', verbose_name='Rasmi')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mutaxassisligi/Yo'nalishi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ilmiy rahbar',
                'verbose_name_plural': 'Ilmiy rahbarlar',
                'db_table': 'scientific_supervisors',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
