# Generated by Django 6.0.2 on 2026-05-27 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_scientificsupervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificsupervisor',
            name='max_students',
            field=models.PositiveIntegerField(default=5, help_text="Bu rahbar qabul qila oladigan eng ko'p talabalar soni", verbose_name='Maks. talabalar soni'),
        ),
        migrations.CreateModel(
            name='SupervisorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutish'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('decision_reason', models.TextField(blank=True, null=True, verbose_name='Qaror sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaror qabul qilingan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.scientificsupervisor', verbose_name='Ilmiy rahbar')),
            ],
            options={
                'verbose_name': "Rahbarlik so'rovi",
                'verbose_name_plural': "Rahbarlik so'rovlari",
                'db_table': 'supervisor_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
