# Generated by Django 6.0.2 on 2026-05-27 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_scientificsupervisor_max_students_supervisorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('matematika', '1. Xalqaro matematika fan olimpiadalariga tayyorlov'), ('kimyo', '2. Xalqaro kimyo fan olimpiadalariga tayyorlov'), ('ingliz_tili', '3. Xalqaro ingliz tili fan olimpiadalariga tayyorlov'), ('falsafa', '4. Xalqaro falsafa fan olimpiadasiga tayyorlov'), ('iqtisodiyot', '5. Xalqaro iqtisodiyotga oid fanlar olimpiadasiga tayyorlov'), ('fizika', '6. Xalqaro fizika fan olimpiadasiga tayyorlov'), ('it', '7. Xalqaro IT olimpiadalariga tayyorlov'), ('innovatsiya', '8. Xalqaro ilmiy-innovatsion mazmundagi tanlovlarga tayyorlov')], max_length=30, unique=True, verbose_name='Olimpiada kodi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('short_intro', models.TextField(help_text='Olimpiada haqida qisqa tanishtirish', verbose_name='Qisqacha kirish')),
                ('required_skills', models.TextField(blank=True, help_text="Bu olimpiadaga arizachilar uchun zarur ko'nikmalar", verbose_name="Talab qilingan ko'nikmalar")),
                ('knowledge_areas', models.TextField(blank=True, help_text='Tekshiriladigan bilim sohalari va mavzular', verbose_name='Bilim sohalari')),
                ('self_check_text', models.TextField(blank=True, help_text="Talaba o'z bilimlarini sinash uchun namunaviy savollar va mavzular", verbose_name="O'zini tekshirish uchun matn")),
                ('task_file', models.FileField(blank=True, help_text="PDF, Word yoki boshqa formatdagi topshiriqlar to'plami", null=True, upload_to='olympiad_tasks/', verbose_name='Topshiriqlar fayli')),
                ('additional_info', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Olimpiada dasturi',
                'verbose_name_plural': 'Olimpiada dasturlari',
                'db_table': 'olympiad_programs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(blank=True, null=True, verbose_name="Motivatsiya / Qo'shimcha matn")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('reviewed', "Ko'rib chiqildi"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holat')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_applications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.olympiadprogram', verbose_name='Olimpiada')),
            ],
            options={
                'verbose_name': 'Olimpiadaga ariza',
                'verbose_name_plural': 'Olimpiadaga arizalar',
                'db_table': 'olympiad_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
