# Generated by Django 6.0.2 on 2026-05-27 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_demo_olympiad_programs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiadapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Olimpiada arizasi', 'verbose_name_plural': 'Olimpiada arizalari'},
        ),
        migrations.AddField(
            model_name='olympiadapplication',
            name='application_type',
            field=models.CharField(choices=[('olympiad', 'Olimpiada'), ('volunteer', 'Volontyor')], default='olympiad', max_length=20, verbose_name='Ariza turi'),
        ),
        migrations.AlterField(
            model_name='olympiadapplication',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.olympiadprogram', verbose_name='Olimpiada'),
        ),
    ]
