# Generated by Django 6.0.2 on 2026-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_olympiad_application_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherregulation',
            name='regulation_link',
            field=models.URLField(blank=True, help_text='Tashqi nizom havolasi (https://...). Fayl yuklash shart emas.', null=True, verbose_name='Nizom havolasi'),
        ),
        migrations.AlterField(
            model_name='researcherregulation',
            name='file',
            field=models.FileField(blank=True, help_text='Yoki nizom faylini yuklang (PDF, DOCX). Havola kiritilsa, fayl ixtiyoriy.', null=True, upload_to='regulations/', verbose_name='Fayl'),
        ),
    ]
