# Generated by Django 6.0.2 on 2026-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_researcher_regulation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='information_letter_link',
            field=models.URLField(blank=True, help_text='Tashqi axborot xati havolasi (https://...). Fayl yuklash shart emas.', null=True, verbose_name='Axborot xati havolasi'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='information_letter',
            field=models.FileField(blank=True, help_text='Yoki axborot xati faylini yuklang (PDF). Havola kiritilsa, fayl ixtiyoriy.', null=True, upload_to='conferences/info_letters/', verbose_name="Ma'lumot xati"),
        ),
    ]
