# Generated by Django 6.0.2 on 2026-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_conference_information_letter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='statescholarship',
            name='regulation_file',
            field=models.FileField(blank=True, help_text='Yoki nizom faylini yuklang (PDF). Havola kiritilsa, fayl ixtiyoriy.', null=True, upload_to='state_scholarships/regulations/', verbose_name='Nizom fayli'),
        ),
        migrations.AlterField(
            model_name='statescholarship',
            name='application_link',
            field=models.URLField(blank=True, help_text='Ariza topshirish uchun havola (https://...) — ixtiyoriy', null=True, verbose_name='Ariza topshirish havolasi'),
        ),
        migrations.AlterField(
            model_name='statescholarship',
            name='regulation_link',
            field=models.URLField(blank=True, help_text='Stipendiya nizomiga tashqi havola (https://...). Fayl yuklash shart emas.', null=True, verbose_name='Nizom havolasi'),
        ),
    ]
