# Generated by Django 6.0.2 on 2026-05-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_state_scholarship_regulation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='buxduscholarship',
            name='regulation_link',
            field=models.URLField(blank=True, help_text='Stipendiya nizomiga tashqi havola (https://...). Fayl yuklash shart emas.', null=True, verbose_name='Nizom havolasi'),
        ),
        migrations.AlterField(
            model_name='buxduscholarship',
            name='application_link',
            field=models.URLField(blank=True, help_text='Onlayn ariza topshirish uchun havola', null=True, verbose_name='Ariza topshirish havolasi'),
        ),
        migrations.AlterField(
            model_name='buxduscholarship',
            name='regulation_file',
            field=models.FileField(blank=True, help_text='Yoki nizom faylini yuklang (PDF, DOCX). Havola kiritilsa, fayl ixtiyoriy.', null=True, upload_to='scholarships/regulations/', verbose_name='Nizom fayli'),
        ),
    ]
