# Generated by Django 6.0.2 on 2026-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_buxdu_scholarship_regulation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='buxduwinnerdatabase',
            name='file_link',
            field=models.URLField(blank=True, help_text='Tashqi fayl havolasi (https://...). Fayl yuklash shart emas.', null=True, verbose_name='Fayl havolasi'),
        ),
        migrations.AlterField(
            model_name='buxduwinnerdatabase',
            name='file',
            field=models.FileField(blank=True, help_text="Yoki g'oliblar ro'yxatini yuklang (PDF, XLSX, DOCX).", null=True, upload_to='buxdu_winners/', verbose_name='Fayl'),
        ),
    ]
