# Generated by Django 6.0.2 on 2026-05-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_buxdu_winner_database_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentedstudentdatabase',
            name='file_link',
            field=models.URLField(blank=True, help_text='Tashqi fayl havolasi (https://...). Fayl yuklash shart emas.', null=True, verbose_name='Fayl havolasi'),
        ),
        migrations.AlterField(
            model_name='talentedstudentdatabase',
            name='file',
            field=models.FileField(blank=True, help_text="Yoki iqtidorli talabalar ro'yxatini yuklang (PDF, DOCX, XLSX).", null=True, upload_to='talented_students/', verbose_name='Fayl'),
        ),
    ]
