# Generated by Django 6.0.2 on 2026-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_talented_database_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='information_letter_link',
            field=models.URLField(blank=True, help_text='Tashqi axborot xati havolasi (https://...). Fayl yuklash shart emas.', null=True, verbose_name='Axborot xati havolasi'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='information_letter',
            field=models.FileField(blank=True, help_text="Yoki olimpiada haqida rasmiy ma'lumot xatini yuklang (PDF).", null=True, upload_to='olympiads/info_letters/', verbose_name="Ma'lumot xati"),
        ),
    ]
