# Generated by Django 6.0.2 on 2026-05-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_olympiad_information_letter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='image_link',
            field=models.URLField(blank=True, help_text='Tashqi rasm havolasi (https://...). Rasm yuklash shart emas.', null=True, verbose_name='Rasm havolasi'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='image',
            field=models.ImageField(blank=True, help_text="Yoki olimpiada kartasida ko'rsatiladigan rasmni yuklang (tavsiya: 400x300px)", null=True, upload_to='olympiads/images/', verbose_name='Olimpiada rasmi'),
        ),
    ]
