# Generated by Django 6.0.2 on 2026-05-30 18:44

from django.db import migrations, models


def normalize_status(apps, schema_editor):
    """Eski status qiymatlarini yangi tizimga moslash.

    Avval status maydoni ham rol ('talaba'), ham holatni ('iqtidorli') saqlardi.
    Endi: status faqat 'oddiy'/'iqtidorli'. 'iqtidorli' bo'lmagan barcha qiymatlar
    'oddiy' ga aylantiriladi. Rol esa hammaga standart 'talaba' bo'lib qoladi.
    """
    User = apps.get_model('main', 'User')
    User.objects.exclude(status='iqtidorli').update(status='oddiy')


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_olympiad_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('talaba', 'Talaba'), ('foydalanuvchi', 'Foydalanuvchi'), ('oqituvchi', "O'qituvchi")], default='talaba', help_text="Foydalanuvchi roli (ro'yxatdan o'tishda tanlanadi)", max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('oddiy', 'Oddiy'), ('iqtidorli', 'Iqtidorli')], default='oddiy', help_text='Iqtidorli yoki oddiy (admin tomonidan belgilanadi)', max_length=50, verbose_name='Talaba holati'),
        ),
        migrations.RunPython(normalize_status, reverse_noop),
    ]
