# Generated by Django 6.0.2 on 2026-09-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_user_role_and_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('database', 'Database'), ('website', 'Website / Template'), ('faq', 'FAQ'), ('business_logic', 'Business logic'), ('documentation', 'Documentation'), ('other', 'Other')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('source_file', models.CharField(blank=True, default='', max_length=300)),
                ('priority', models.PositiveSmallIntegerField(default=50, help_text='Yuqori = muhimroq (1–100)')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('search_text', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Knowledge chunk',
                'verbose_name_plural': 'Knowledge chunks',
                'db_table': 'knowledge_chunks',
                'ordering': ['-priority', '-indexed_at'],
                'indexes': [models.Index(fields=['source_type', 'category'], name='knowledge_c_source__2efffd_idx'), models.Index(fields=['content_hash'], name='knowledge_c_content_5d0ed0_idx')],
            },
        ),
    ]
