# Generated by Django 6.0.2 on 2026-09-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_knowledge_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mening faoliyatim', help_text='Profilida ko‘rinadigan tugma nomi', max_length=120, verbose_name='Tugma matni')),
                ('link', models.URLField(help_text='https://... — talaba shu sahifaga o‘tkaziladi', verbose_name='Faoliyat kuzatuv sayti (havola)')),
                ('is_active', models.BooleanField(default=True, help_text='O‘chirilsa, profilida tugma ko‘rinmaydi', verbose_name='Faol')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Talaba faoliyatini kuzatish',
                'verbose_name_plural': 'Talaba faoliyatini kuzatish',
                'db_table': 'student_activity_link',
            },
        ),
    ]
