"""
Django settings for xalikova_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s*(=&6ozvgz8u#vfddf6perq!v1#mz3x0z8557b$$5=xb(+r8d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# CSRF settings
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xalikova_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'django_templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xalikova_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("DB_NAME"),
        'USER': os.environ.get("DB_USER"),
        'PASSWORD': os.environ.get("DB_PASSWORD"),
        'HOST': os.environ.get("DB_HOST", "localhost"),
        'PORT': os.environ.get("DB_PORT", "5432"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Custom User Model
AUTH_USER_MODEL = 'main.User'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'main.backends.EmailBackend',  # Email bilan login qilish
    'django.contrib.auth.backends.ModelBackend',  # Standart backend (admin uchun)
]

# Login/Logout URLs
LOGIN_URL = 'main:login'
LOGIN_REDIRECT_URL = 'main:home'
LOGOUT_REDIRECT_URL = 'main:home'

# Session settings - prevent auto-login on refresh
SESSION_COOKIE_AGE = 86400  # 24 soat (sekund hisobida)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Brauzer yopilganda session tugaydi
SESSION_SAVE_EVERY_REQUEST = False  # Har safar request bo'lganda session yangilanmasin

# Media files (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Yosh Tadqiqotchi Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Yosh Tadqiqotchi",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Yosh Tadqiqotchi",

    # Logo to use for your site, must be present in static files
    "site_logo": "assets/logo.png",

    # Welcome text on the login screen
    "welcome_sign": "Yosh Tadqiqotchi platformasiga xush kelibsiz",

    # Copyright on the footer
    "copyright": "Yosh Tadqiqotchi 2026",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "main.User",

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": "profile_image",

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # Icons to use for the main navigation
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.User": "fas fa-user-graduate",
        "main.Announcement": "fas fa-bullhorn",
        "main.Course": "fas fa-book-reader",
        "main.Module": "fas fa-puzzle-piece",
        "main.Survey": "fas fa-poll",
        "main.TalentedStudentDatabase": "fas fa-star",
        "main.StateScholarship": "fas fa-award",
        "main.BuxduScholarship": "fas fa-graduation-cap",
        "main.BuxduWinnerDatabase": "fas fa-trophy",
        "main.Olympiad": "fas fa-medal",
        "main.BuxduOlympiadWinner": "fas fa-trophy",
        "main.BuxduOlympiad": "fas fa-flag",
        "main.OakDatabase": "fas fa-book",
        "main.Conference": "fas fa-users",
        "main.DissertationBank": "fas fa-scroll",
        "main.ArticleBank": "fas fa-file-alt",
        "main.ResearcherRegulation": "fas fa-gavel",
        "main.TestSet": "fas fa-clipboard-list",
        "main.Question": "fas fa-question-circle",
        "main.Answer": "fas fa-check-circle",
        "main.UserCourseProgress": "fas fa-chart-line",
        "main.UserModuleProgress": "fas fa-tasks",
        "main.UserTestResult": "fas fa-chart-bar",
        "main.Certificate": "fas fa-certificate",
        "main.AssessmentTest": "fas fa-file-signature",
        "main.AssessmentTestResult": "fas fa-poll-h",
    },

    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Bosh sahifa",  "url": "admin:index", "permissions": ["auth.view_user"]},
        # external url that opens in a new window (Permissions can be added)
        {"name": "Saytni ko'rish", "url": "/", "new_window": True},
    ],

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps to base side menu ordering off of (does not need to contain all apps)
    "order_with_respect_to": ["main", "auth"],

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.0,5.11.1
    # for the full list of 5.13.0 free icon classes
    
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    # Change colors - SINGLE format (barcha maydonlar bitta sahifada)
    "changeform_format": "single",
    "changeform_format_overrides": {"auth.user": "single", "auth.group": "single"},
    
    # Login sahifasida logo kichikroq bo'lishi uchun
    "login_logo": None,  # Logo o'chirildi
    "site_logo_classes": "img-circle",  # Logo aylana shakli
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-primary navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    # Admin logo o'lchami
    "custom_css": "admin/custom_admin.css",
}
